### PR TITLE
use docker pkg/sockets package to create net.Listeners

### PR DESCRIPTION
**Pull request by bufdev**
This is basically just a copy from https://github.com/peter-edge/go-dockervolume, so if there's any specific cleanup from that you want, let me know.

### CODE REVIEW

**Comment by calavera** [comment]
do you mind to remove everything we don't need from the `connection.go` file? maybe we don't need anything from there anymore.

**Comment by bufdev** [comment]
deleted - I'm sure you'll do this but you prob want to run this change against some of your plugins to make sure it really works

**Comment by bufdev** [comment]
ping

**Comment by calavera** [comment]
Sorry for the late review, thank you! I'm going to merge it.

**Pull request merged**
